# Site wide configuration

title: Ambients
locale: en_US
description: "Peer-to-Peer Programs and Data"
logo: ambients-avatar.png
# wordless_logo: favicon.png
search: true
author: "Haja Networks"
url: https://ambients.org
github: https://github.com/ambientsprotocol
# Site owner
baseurl: https://ambients.org
owner:
  name: Haja Networks
  email: community@haja.io
  # twitter: # TODO
  github: ambientsprotocol
  url: https://haja.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-twitter-plugin

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
# Excluding most of the usual suspects
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "gulpfile.js", "package.json", "package-lock.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor", "theme-setup"]
